repos:
  -   repo: https://github.com/python-poetry/poetry
      rev: 1.7.1
      hooks:
        -   id: poetry-check
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
