# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    # You can also specify other tool versions:
    # nodejs: "19"
  jobs:
    post_create_environment:
      # From https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --all-extras
      # Attempt to remedy repeated errors: ModuleNotFoundError: No module named 'typing_extensions'
      #- pip install typing_extensions
      - poetry version $(git describe --tags --abbrev=0)
      - cd docs;python gen_api_lists.py

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#    install:
#    - requirements: docs/requirements.txt