name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    permissions:
      contents: write
    steps:
      - uses: ./.github/workflows/_setup.yml
      # Build library.
      - name: Get version
        id: version
        run: echo "version=$(git describe --tags --abbrev=0 | cut -c 2)"- >> $GITHUB_OUTPUT
      - name: Set version from Git tag
        run: poetry version ${{ steps.version.outputs.version }}
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Poetry Build
        run: poetry build
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist
      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.changelog.outputs.changelog}}
          files: ./dist

  publish-pypi:
    needs: ['release']
    runs-on: ubuntu-latest
    environment: 'release'
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
      # Try uploading to Test PyPI first, in case something fails.
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: artifact/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: artifact/